v4.0.13

diff --git a/synology/scripts/postinst b/synology/scripts/postinst
--- a/synology/scripts/postinst
+++ b/synology/scripts/postinst
@@ -2,18 +2,20 @@
 spk_su="/opt/sbin/spk_su"
 privilege_file=`dirname $0`/../conf/privilege
 
-if [ -w "${privilege_file}" ]; then
-    # DSM 7 beta
-    # privilege_file is writable by package
-    sed -i 's/package/root/g' "${privilege_file}"
-elif [ -e "${privilege_file}" ]; then
-    # DSM 7 release
-    # privilege_file exists but is not writable by package
-    if [ -x "${spk_su}" ]; then
-        "${spk_su}" "${SYNOPKG_PKGNAME}"
-    else
-        echo "Failed to change ${privilege_file}" > /dev/stderr
-        exit 5
+if [ -f "${spk_su}" ]; then
+    if [ -w "${privilege_file}" ]; then
+        # DSM 7 beta
+        # privilege_file is writable by package
+        sed -i 's/package/root/g' "${privilege_file}"
+    elif [ -e "${privilege_file}" ]; then
+        # DSM 7 release
+        # privilege_file exists but is not writable by package
+        if [ -x "${spk_su}" ]; then
+            "${spk_su}" "${SYNOPKG_PKGNAME}"
+        else
+            echo "Failed to change ${privilege_file}" > /dev/stderr
+            #exit 5
+        fi
     fi
 fi
 
